"""update courses and lessons tables

Revision ID: 84a3e8bd4bcc
Revises: 19e50a52d38b
Create Date: 2026-04-19 08:36:09.173775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a3e8bd4bcc'
down_revision: Union[str, Sequence[str], None] = '19e50a52d38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('lessons', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lessons', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
