"""update courses and lessons tables v2

Revision ID: 892ec8e4e0f5
Revises: 84a3e8bd4bcc
Create Date: 2026-04-19 08:39:15.057391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892ec8e4e0f5'
down_revision: Union[str, Sequence[str], None] = '84a3e8bd4bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('lessons', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lessons', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
